"""add organizations, invitations, user org fields

Revision ID: 8c44c66bdb1d
Revises: 
Create Date: 2026-03-03 12:06:50.756126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c44c66bdb1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('org_role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('onboarding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'onboarding_data')
    op.drop_column('users', 'org_role')
    op.drop_column('users', 'org_id')
    # ### end Alembic commands ###
